set(_AMENT_PACKAGE_NAME "gazebo_car_description")
set(gazebo_car_description_VERSION "0.0.1")
set(gazebo_car_description_MAINTAINER "workspace <workspace@example.com>")
set(gazebo_car_description_BUILD_DEPENDS )
set(gazebo_car_description_BUILDTOOL_DEPENDS "ament_cmake")
set(gazebo_car_description_BUILD_EXPORT_DEPENDS )
set(gazebo_car_description_BUILDTOOL_EXPORT_DEPENDS )
set(gazebo_car_description_EXEC_DEPENDS "ament_index_python" "geometry_msgs" "launch" "launch_ros" "python3-numpy" "python3-opencv" "rclpy" "robot_state_publisher" "ros_gz_bridge" "ros_gz_sim" "sensor_msgs" "std_msgs" "joint_state_publisher" "tf2_ros" "visualization_msgs")
set(gazebo_car_description_TEST_DEPENDS )
set(gazebo_car_description_GROUP_DEPENDS )
set(gazebo_car_description_MEMBER_OF_GROUPS )
set(gazebo_car_description_DEPRECATED "")
set(gazebo_car_description_EXPORT_TAGS)
list(APPEND gazebo_car_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
