set(_AMENT_PACKAGE_NAME "race_interfaces")
set(race_interfaces_VERSION "0.1.0")
set(race_interfaces_MAINTAINER "urrc_hanla <maintainer@example.com>")
set(race_interfaces_BUILD_DEPENDS "rosidl_default_generators" "std_msgs" "nav_msgs")
set(race_interfaces_BUILDTOOL_DEPENDS "ament_cmake")
set(race_interfaces_BUILD_EXPORT_DEPENDS "std_msgs" "nav_msgs")
set(race_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(race_interfaces_EXEC_DEPENDS "rosidl_default_runtime" "std_msgs" "nav_msgs")
set(race_interfaces_TEST_DEPENDS )
set(race_interfaces_GROUP_DEPENDS )
set(race_interfaces_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(race_interfaces_DEPRECATED "")
set(race_interfaces_EXPORT_TAGS)
list(APPEND race_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
