set(_AMENT_PACKAGE_NAME "camera_bringup")
set(camera_bringup_VERSION "0.1.0")
set(camera_bringup_MAINTAINER "ww <ww@todo.todo>")
set(camera_bringup_BUILD_DEPENDS )
set(camera_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(camera_bringup_BUILD_EXPORT_DEPENDS )
set(camera_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(camera_bringup_EXEC_DEPENDS "ament_index_python" "launch" "launch_ros" "realsense2_camera" "sensor_msgs")
set(camera_bringup_TEST_DEPENDS )
set(camera_bringup_GROUP_DEPENDS )
set(camera_bringup_MEMBER_OF_GROUPS )
set(camera_bringup_DEPRECATED "")
set(camera_bringup_EXPORT_TAGS)
list(APPEND camera_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
